# Generated by Django 4.2.10 on 2025-05-14 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='a_faire', max_length=20, verbose_name='statut')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='budget')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('derniere_modification', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='clients.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['client'], name='projets_pro_client__a35cb2_idx'), models.Index(fields=['statut'], name='projets_pro_statut_2c59ef_idx'), models.Index(fields=['date_debut'], name='projets_pro_date_de_1375de_idx')],
            },
        ),
    ]
