# Generated by Django 4.2.10 on 2025-05-14 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('probabilite', models.IntegerField(default=50, help_text='Probabilité de conclusion (0-100%)', verbose_name='probabilité (%)')),
                ('etape', models.CharField(choices=[('prospect', 'Prospect'), ('qualification', 'Qualification'), ('proposition', 'Proposition'), ('negociation', 'Négociation'), ('conclusion', 'Conclusion')], default='prospect', max_length=20, verbose_name='étape')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_conclusion_estimee', models.DateField(blank=True, null=True, verbose_name='date de conclusion estimée')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('derniere_modification', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunites', to='clients.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'opportunité',
                'verbose_name_plural': 'opportunités',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('consulte', 'Consulté'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='brouillon', max_length=20, verbose_name='statut')),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('contenu', models.JSONField(default=dict, verbose_name='contenu')),
                ('date_derniere_modification', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('opportunite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='opportunites.opportunite', verbose_name='opportunité')),
            ],
            options={
                'verbose_name': 'devis',
                'verbose_name_plural': 'devis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='opportunite',
            index=models.Index(fields=['client'], name='opportunite_client__921a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunite',
            index=models.Index(fields=['etape'], name='opportunite_etape_43b7b8_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunite',
            index=models.Index(fields=['montant'], name='opportunite_montant_794ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='devis',
            index=models.Index(fields=['opportunite'], name='opportunite_opportu_b2a931_idx'),
        ),
        migrations.AddIndex(
            model_name='devis',
            index=models.Index(fields=['statut'], name='opportunite_statut_52f7e5_idx'),
        ),
        migrations.AddIndex(
            model_name='devis',
            index=models.Index(fields=['version'], name='opportunite_version_fa170d_idx'),
        ),
    ]
