# Generated by Django 4.2.10 on 2025-05-14 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('taches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='assigne_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='assigné à'),
        ),
        migrations.AddField(
            model_name='tache',
            name='client_associe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches', to='clients.client', verbose_name='client associé'),
        ),
        migrations.AddField(
            model_name='tache',
            name='projet_associe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches', to='projets.projet', verbose_name='projet associé'),
        ),
        migrations.AddIndex(
            model_name='tache',
            index=models.Index(fields=['assigne_a'], name='taches_tach_assigne_6adc4a_idx'),
        ),
        migrations.AddIndex(
            model_name='tache',
            index=models.Index(fields=['client_associe'], name='taches_tach_client__108b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='tache',
            index=models.Index(fields=['projet_associe'], name='taches_tach_projet__326262_idx'),
        ),
        migrations.AddIndex(
            model_name='tache',
            index=models.Index(fields=['statut'], name='taches_tach_statut_1b1ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='tache',
            index=models.Index(fields=['priorite'], name='taches_tach_priorit_98f17f_idx'),
        ),
        migrations.AddIndex(
            model_name='tache',
            index=models.Index(fields=['date_echeance'], name='taches_tach_date_ec_86b1f2_idx'),
        ),
    ]
