# Generated by Django 4.2.10 on 2025-05-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('societe', models.CharField(blank=True, max_length=100, verbose_name='société')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('categorie', models.CharField(choices=[('prospect', 'Prospect'), ('client', 'Client'), ('vip', 'VIP'), ('inactif', 'Inactif')], default='prospect', max_length=20, verbose_name='catégorie')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('derniere_modification', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['nom'], name='clients_cli_nom_0cf00c_idx'), models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx'), models.Index(fields=['categorie'], name='clients_cli_categor_978ce5_idx')],
            },
        ),
    ]
